// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usuarios.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUsuario = `-- name: GetUsuario :one
SELECT id, nome, cpf, email, email_verificado, hash_senha, criado_em, atualizado_em FROM usuarios WHERE id = $1
`

// GetUsuario busca um usuário pelo ID informado.
func (q *Queries) GetUsuario(ctx context.Context, id pgtype.UUID) (Usuario, error) {
	row := q.db.QueryRow(ctx, getUsuario, id)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.CPF,
		&i.Email,
		&i.EmailVerificado,
		&i.HashSenha,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const getUsuarioByCPF = `-- name: GetUsuarioByCPF :one
SELECT id, nome, cpf, email, email_verificado, hash_senha, criado_em, atualizado_em FROM usuarios WHERE cpf = $1
`

// GetUsuarioByCPF busca um usuário pelo CPF informado.
func (q *Queries) GetUsuarioByCPF(ctx context.Context, cpf string) (Usuario, error) {
	row := q.db.QueryRow(ctx, getUsuarioByCPF, cpf)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.CPF,
		&i.Email,
		&i.EmailVerificado,
		&i.HashSenha,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const saveUsuario = `-- name: SaveUsuario :one
INSERT INTO usuarios (nome, cpf, email, email_verificado, hash_senha)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, nome, cpf, email, email_verificado, hash_senha, criado_em, atualizado_em
`

type SaveUsuarioParams struct {
	Nome            string
	CPF             string
	Email           string
	EmailVerificado bool
	HashSenha       pgtype.Text
}

// SaveUsuario salva um novo usuário no banco de dados.
func (q *Queries) SaveUsuario(ctx context.Context, arg SaveUsuarioParams) (Usuario, error) {
	row := q.db.QueryRow(ctx, saveUsuario,
		arg.Nome,
		arg.CPF,
		arg.Email,
		arg.EmailVerificado,
		arg.HashSenha,
	)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.CPF,
		&i.Email,
		&i.EmailVerificado,
		&i.HashSenha,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const updateSenhaUsuario = `-- name: UpdateSenhaUsuario :exec
UPDATE usuarios SET
    hash_senha = $2,
    atualizado_em = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateSenhaUsuarioParams struct {
	ID        pgtype.UUID
	HashSenha pgtype.Text
}

// UpdateSenhaUsuario atualiza o hash da senha de um usuário.
func (q *Queries) UpdateSenhaUsuario(ctx context.Context, arg UpdateSenhaUsuarioParams) error {
	_, err := q.db.Exec(ctx, updateSenhaUsuario, arg.ID, arg.HashSenha)
	return err
}
